version: '3.9'

networks:
  entity-filter:
    driver: bridge

services:
  api:
    container_name: api-entity-filter
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5434/${POSTGRES_DB}?schema=public
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - ${API_PORT}:3000
    depends_on:
      - postgres
    networks:
      - entity-filter
  postgres:
    image: postgres
    container_name: postgres-entity-filter
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - '5434:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - entity-filter

volumes:
  postgres:
  redis:
    driver: local